/**
 * Every visible string of the page, in English. Adding another language means
 * adding a table with the same keys. No dashes, no filler.
 */
import { formatBytes } from "./view.js";

export const S = {
  brand: "fer-2013",
  title: "Facial expression classifier",
  lede: "A ResNet18 trained on FER-2013. It finds the faces in your photo, picks one of seven expressions for each, and shows where it looked. Everything runs in this tab.",
  navCode: "Code",
  navApi: "API",
  navLabel: "Project links",
  stageAria: "Photo",
  resultsAria: "Results",
  plateAria: "Analyze the sample photo",
  choosePhoto: "Choose a photo",
  useCamera: "Use your camera",
  stopCamera: "Stop the camera",
  tryExample: "Use the sample photo",
  dropHint: "You can also drop a photo anywhere on the page.",
  plateCaption: "Sample photo",
  formats: "JPEG, PNG or WebP, up to 10\u00a0MB.",
  privacy: "Photos and camera frames never leave your device.",
  cameraStarting: "Starting the camera",
  liveLabel: "Live camera, mirrored",
  liveStatus: (n, fps) => `${n === 1 ? "1 face" : `${n} faces`}, ${fps.toFixed(1)} analyses per second`,
  loadingModel: (loaded, total) => `Downloading the model, ${formatBytes(loaded)} of ${formatBytes(total)}`,
  busy: "Still working on the previous photo.",
  detecting: "Looking for faces",
  result: (n, ms) => (n === 1 ? `1 face found in ${Math.round(ms)} ms.` : `${n} faces found in ${Math.round(ms)} ms.`),
  stripAria: "Pick a face",
  noFace: "No face found.",
  noFaceTips: "Try a sharper, front-facing photo with even light.",
  faceLabel: (i) => `Face ${i}`,
  original: "What the model saw",
  heatmap: "Where it looked",
  heatmapAlt: (i, emotion) => `Heatmap for face ${i}, predicted ${emotion}`,
  stageLabel: (n) => (n === 0 ? "Uploaded photo, no faces found" : n === 1 ? "Uploaded photo with 1 face marked" : `Uploaded photo with ${n} faces marked`),
  timings: { detect: "Detection", classify: "Classification", gradcam: "Grad-CAM++", runtime: "Runtime" },
  backend: "WebAssembly, 1 thread",
  limitation: "Expression labels read off a face are unreliable. This model gets about 71% right on FER-2013.",
  limitationLink: "Limitations",
  retry: "Try again",
  emotions: { angry: "angry", disgust: "disgust", fear: "fear", happy: "happy", sad: "sad", surprise: "surprise", neutral: "neutral" },
  errors: {
    format: "That file type isn't supported. Use JPEG, PNG or WebP.",
    size: "That file is over 10 MB.",
    pixels: "That image is over 25 megapixels.",
    integrity: "The downloaded model failed its checksum. Try again.",
    download: "Couldn't download the model. Check your connection and try again.",
    decode: "Couldn't read that image.",
    inference: "Something went wrong while analyzing the photo.",
    unsupported: "This browser has no WebAssembly SIMD, which the model needs.",
    cameraDenied: "Camera access is blocked. Allow it in the site settings of your browser and try again.",
    cameraMissing: "No camera found.",
    cameraBusy: "The camera is in use by another app.",
    cameraUnsupported: "This browser cannot open the camera here.",
  },
};
